<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "rere"
 *
 * Auto generated by Extension Builder 2015-01-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Result Repository',
    'description' => 'Notenverwaltungs Extension für Typo3',
    'category' => 'plugin',
    'author' => 'Felix Hohlwegler, Sarah Kieninger, Tim Wacker, Nejat Balta, Tobias Brockner, Nicolas Tedjadharma',
    'author_email' => 'info@felix-hohlwegler.de, sarah.kieninger@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-6.2.9',
            'fluid' => '6.0',
            'extbase' => '6.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
